import Head from 'next/head'
import Menu from "../components/Menu"
import Footer from "../components/footer"
import ContactForm from "../components/form"
import ArrowCircleDownIcon from '@mui/icons-material/ArrowCircleDown';

export default function Contact() {
  return (
    <div className="dark:bg-gray-800 bg-gray-100 w-screen">
      <Head>
        <title>Jonuel portfolio contact</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Menu />
      
      <div className="grid place-items-center mt-14 mb-4 px-14 md:px-0">
      <h1 className="text-center font-bold text-2xl dark:text-white text-black mb-8">send your message</h1>
      <div className="md:w-4/6 mb-24">
      <ContactForm />
      </div>
      </div>
      <Footer />
    </div>
  )
}