import Head from 'next/head'
import Menu from "../components/Menu"
import Main from "../components/Main"
import Footer from "../components/footer"
// import FormLInk from "../components/formLink"
import About from "../components/about"
import Skill from "../components/Skills"
import Project from "../components/project"

export default function Home() {
  return (
    <div className="dark:bg-gray-800 bg-gray-100 w-screen">
      <Head>
        <title>Jonuel portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Menu />
      <Main />
      <About />
      <Project />
      {/* <FormLInk /> */}
      <Skill />
      <Footer />
    </div>
  )
}
